blank_issues_enabled: false
contact_links:
  - name: I have a question or need support
    url: hhttps://github.com/timmo001/system-bridge/discussions
    about: Please use the discussions area for getting help or asking questions.
