name: Request a new feature
description: Request a new feature or enhancement.
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: >-
        Details of the feature and what should be added.
