---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  # schedule:
  #   - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  deploy-container:
    uses: ./.github/workflows/deploy-container.yml
  package:
    uses: ./.github/workflows/package.yml
