---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  deploy-release:
    name: 👷 Deploy to Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - name: windows
          - name: linux
          - name: macos
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: ⤵️ Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: pkg-${{ matrix.os.name }}
          path: out/make/**/**
          workflow: ci.yml
          workflow_conclusion: success
      - name: ⬆ Upload Artifacts to Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: out/make/**/**
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
