---
name: Deploy Container

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-container-amd64:
    uses: timmo001/workflows/.github/workflows/deploy-container-linux.yml@master
    with:
      architecture: amd64
      container-slug: system-bridge
