---
name: Package

# yamllint disable-line rule:truthy
on:
  workflow_run:
    types:
      - completed
    workflows:
      - Deploy
  workflow_dispatch:

jobs:
  package-python-pyinstaller-linux:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-linux.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir \
        --icon "resources/system-bridge.png" \
        --name "systembridge" \
        --collect-all "plyer" \
        --collect-all "systembridgeshared" \
        --collect-all "systembridgebackend" \
        --collect-all "systembridgecli" \
        --collect-all "systembridgefrontend" \
        --collect-all "systembridgegui" \
      create-setup: true
      entry-point-file: systembridge.py
      pre-package-command: |
        pip install \
          --upgrade \
          --pre \
          systembridgeshared \
          systembridgebackend \
          systembridgecli \
          systembridgefrontend \
          systembridgegui
  package-python-pyinstaller-windows:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-windows.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir `
        --icon "resources/system-bridge.ico" `
        --name "systembridge" `
        --collect-all "plyer" `
        --collect-all "pywin32" `
        --collect-all "systembridgeshared" `
        --collect-all "systembridgebackend" `
        --collect-all "systembridgecli" `
        --collect-all "systembridgefrontend" `
        --collect-all "systembridgegui" `
        --collect-all "systembridgewindowssensors" `
      create-setup: true
      entry-point-file: systembridge.py
      pre-package-command: |
        pip install `
          --upgrade `
          --pre `
          pywin32 `
          systembridgeshared `
          systembridgebackend `
          systembridgecli `
          systembridgefrontend `
          systembridgegui `
          systembridgewindowssensors
