---
name: "Package Application"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  release:
    types:
      - published
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  package-backend-linux:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-linux.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir \
        --windowed \
        --icon "resources/system-bridge.png" \
        --name "systembridgebackend" \
        --collect-all "plyer" \
        --collect-all "systembridgeshared" \
        --collect-all "systembridgebackend" \
        --collect-all "systembridgeconnector" \
        --collect-all "systembridgefrontend" \
        --collect-all "typer" \
      create-setup: false
      entry-point-file: application_backend.py
      name: "systembridgebackend"
      pre-package-command: |
        pip install -r requirements_backend_linux.txt
      upload-executable: true
  package-backend-windows:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-windows.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir `
        --windowed `
        --icon "resources/system-bridge.ico" `
        --name "systembridgebackend" `
        --collect-all "plyer" `
        --collect-all "pywin32" `
        --collect-all "winsdk" `
        --collect-all "systembridgeshared" `
        --collect-all "systembridgebackend" `
        --collect-all "systembridgeconnector" `
        --collect-all "systembridgefrontend" `
        --collect-all "systembridgewindowssensors" `
        --collect-all "typer" `
      create-setup: false
      entry-point-file: application_backend.py
      name: "systembridgebackend"
      pre-package-command: |
        pip install -r requirements_backend_windows.txt
      upload-executable: true
  package-gui-linux:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-linux.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir \
        --windowed \
        --icon "resources/system-bridge.png" \
        --name "systembridgegui" \
        --collect-all "systembridgeshared" \
        --collect-all "systembridgegui" \
        --collect-all "typer" \
      create-setup: false
      entry-point-file: application_gui.py
      name: "systembridgegui"
      pre-package-command: |
        pip install -r requirements_gui_linux.txt
      upload-executable: true
  package-gui-windows:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-windows.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir `
        --windowed `
        --icon "resources/system-bridge.ico" `
        --name "systembridgegui" `
        --collect-all "systembridgeshared" `
        --collect-all "systembridgegui" `
        --collect-all "typer" `
      create-setup: false
      entry-point-file: application_gui.py
      name: "systembridgegui"
      pre-package-command: |
        pip install -r requirements_gui_windows.txt
      upload-executable: true
  package-application-linux:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-linux.yml@master
    needs:
      - package-backend-linux
      - package-gui-linux
    with:
      additional-artifact-1-name: "linux-executable-systembridgebackend"
      additional-artifact-1-path: "dist"
      additional-artifact-2-name: "linux-executable-systembridgegui"
      additional-artifact-2-path: "dist"
      additional-pyinstaller-options: |
        --onedir \
        --windowed \
        --icon "resources/system-bridge.png" \
        --name "systembridge" \
        --collect-all "systembridgeshared" \
        --collect-all "typer" \
      create-setup: true
      entry-point-file: application.py
      name: "systembridge"
      pre-package-command: |
        pip install -r requirements_application.txt
      upload-executable: true
  package-application-windows:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-windows.yml@master
    needs:
      - package-backend-windows
      - package-gui-windows
    with:
      additional-artifact-1-name: "windows-executable-systembridgebackend"
      additional-artifact-1-path: "dist"
      additional-artifact-2-name: "windows-executable-systembridgegui"
      additional-artifact-2-path: "dist"
      additional-pyinstaller-options: |
        --onedir `
        --windowed `
        --icon "resources/system-bridge.ico" `
        --name "systembridge" `
        --collect-all "systembridgeshared" `
        --collect-all "typer" `
      create-setup: true
      entry-point-file: application.py
      name: "systembridge"
      pre-package-command: |
        pip install -r requirements_application.txt
      upload-executable: true
