---
name: "Package"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  package-python-pyinstaller-linux:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-linux.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir \
        --windowed \
        --icon "resources/system-bridge.png" \
        --name "systembridge" \
        --collect-all "plyer" \
        --collect-all "systembridgeshared" \
        --collect-all "systembridgebackend" \
        --collect-all "systembridgecli" \
        --collect-all "systembridgefrontend" \
        --collect-all "systembridgegui" \
      create-setup: true
      entry-point-file: systembridge.py
      pre-package-command: |
        pip install -r requirements_linux.txt
  package-python-pyinstaller-windows:
    uses: timmo001/workflows/.github/workflows/package-python-pyinstaller-windows.yml@master
    with:
      additional-pyinstaller-options: |
        --onedir `
        --windowed `
        --icon "resources/system-bridge.ico" `
        --name "systembridge" `
        --collect-all "plyer" `
        --collect-all "pywin32" `
        --collect-all "winsdk" `
        --collect-all "systembridgeshared" `
        --collect-all "systembridgebackend" `
        --collect-all "systembridgecli" `
        --collect-all "systembridgefrontend" `
        --collect-all "systembridgegui" `
        --collect-all "systembridgewindowssensors" `
      create-setup: true
      entry-point-file: systembridge.py
      pre-package-command: |
        pip install -r requirements_windows.txt
