---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: 🏗 Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - name: 🚀 Set Version File
        uses: reedyuk/npm-version@1.1.1
        with:
          version: "${{ steps.release_drafter.outputs.tag_name }}"
      - name: 🚀 Commit
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: |
            "Update version to ${{ steps.release_drafter.outputs.tag_name }}"
          push_options: ""
