---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 Set Version File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ steps.release_drafter.outputs.tag_name }}"
          cat ${{ steps.release_drafter.outputs.tag_name }} > public/version.txt
      - name: 🚀 Commit
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: |
            "Update version file to ${{ steps.release_drafter.outputs.tag_name }}"
