---
name: "Version"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update-version:
    name: ✏️ Update Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.1.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PUSH_TOKEN }}
      - name: ↘️ Get version from systembridgebackend package
        id: get-version
        run: |
          # Get version from systembridgebackend package using requirements_linux.txt
          version=$(grep systembridgebackend requirements_linux.txt | cut -d'=' -f3)
          echo "Version: $version"
          echo "::set-output name=version::$version"
      - name: ✏ Set Version Files
        run: |
          echo "Version: ${{ steps.get-version.outputs.version }}"
          sudo apt update
          sudo apt install -y jq

          # Update version in package.json
          jq --arg version ${{ steps.get-version.outputs.version }} '.version = $version' package.json > package.json.tmp && \
            mv package.json.tmp package.json

          # Update version in src-tauri/tauri.conf.json
          jq --arg version ${{ steps.get-version.outputs.version }} '.version = $version' src-tauri/tauri.conf.json > src-tauri/tauri.conf.json.tmp && \
            mv src-tauri/tauri.conf.json.tmp src-tauri/tauri.conf.json

          # Update version in src-tauri/Cargo.toml
          sed -i '0,/version/s/^version = "\([0-9.]*\)"$/version = "${{ steps.get-version.outputs.version }}"/' src-tauri/Cargo.toml
      - name: ⤵️ Pull latest changes from GitHub
        run: |
          git pull --ff
      - name: 🖊 Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          commit_message: |
            Update version to ${{ steps.get-version.outputs.version }}
          push_options: "--force"
      - name: 🖊️ Create draft release for ${{ steps.get-version.outputs.version }}
        id: release_drafter
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.get-version.outputs.version }}
          tag: ${{ steps.get-version.outputs.version }}
