---
name: "Version"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update-version:
    name: ✏️ Update Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.1.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: ↘️ Get version from systembridgebackend package
        id: get-version
        run: |
          # Get version from systembridgebackend package using requirements_linux.txt
          version=$(grep systembridgebackend requirements_linux.txt | cut -d'=' -f3)
          echo "Version: $version"
          echo "::set-output name=version::$version"
      - name: ✏ Set Version Files
        run: |
          echo "Version: ${{ steps.get-version.outputs.version }}"
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install -y yq jq

          # Update version in nfpm.yml
          yq eval '.version = "${{ steps.get-version.outputs.version }}"' nfpm.yml -i

          # Update version in package.json
          jq --arg version ${{ steps.get-version.outputs.version }} '.version = $version' package.json > package.json.tmp && \
            mv package.json.tmp package.json

          # Update version in src-tauri/tauri.conf.json
          jq --arg version ${{ steps.get-version.outputs.version }} '.version = $version' src-tauri/tauri.conf.json > src-tauri/tauri.conf.json.tmp && \
            mv src-tauri/tauri.conf.json.tmp src-tauri/tauri.conf.json

          # Update version in src-tauri/Cargo.toml
          cd src-tauri
          cargo add cargo-edit
          cargo set-version ${{ steps.get-version.outputs.version }}
      - name: ⤵️ Pull latest changes from GitHub
        run: |
          git pull --ff
      - name: 🖊 Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          commit_message: |
            Update version to ${{ steps.get-version.outputs.version }}
          push_options: "--force"
      - name: 🖊️ Create draft release for ${{ steps.get-version.outputs.version }}
        uses: ncipollo/release-action@v1.14.0
        with:
          draft: true
          generateReleaseNotes: true
          name: ${{ steps.get-version.outputs.version }}
          tag: ${{ steps.get-version.outputs.version }}
